### ISSUE TITLE
barriers invisible

### ISSUE THREAD

**Issue by schuyler1d** [NiklasEi/me_and_my_unicycle#2]
This is a really cool project that I was interested in studying to learn Bevy better. When I build it, everything works except the barriers (things to jump over and the walls) are invisible. I don't see any related assets for that -- do you have ideas of what I might be doing wrong when building it or what the issue might be?

**Comment by NiklasEi** [comment]
Did you build it for web?

I ran out of time for barrier assets, so those just use the debug rendering from rapier. As far as I remember those just didn't work for the web build.

**Comment by NiklasEi** [comment]
What was the command you ran to strat the game?

**Comment by schuyler1d** [comment]
Hi, yes it was for the wasm platform. There's a different issue when building on Linux. Thanks for your help. If I get it working with the barriers either way I'll send a PR.
